name: Deploy Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '2.7'
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Run Deploy
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run action-deploy
      # - name: Git Commit/Push Changes
      #   # You may pin to the exact commit or the version.
      #   # uses: actions-x/commit@803b20e5b72c0425eb7919c42c321e67c5bc5d2d
      #   uses: actions-x/commit@v6
      #   with:
      #     # The committer's email address
      #     # email: # default is ${{ github.actor }}@localhost
      #     # The committer's name
      #     # name: # default is ${{ github.actor }}
      #     # The commit message
      #     # message: # default is Automatically updated using GitHub Actions
      #     # The branch to push the changes back to, defaults to the current branch
      #     branch: gh-pages # default is ${{ github.ref }}
      #     # The files to add separated by space, defaults to every file
      #     # files: # default is .
      #     # The repository to push the code to, defaults to origin (e.g. this repository)
      #     # repository: # default is origin
      #     # The token used to push the code, not needed if you push to the same repository
      #     # token: # default is ${{ github.token }}
      #     # Whether to perform force push
      #     # force: # default is 0
      #     # The working directory that will be used for git commands
      #     directory: ./gh-pages # default is .
      # - name: Push to Github
      #   uses: x-actions/gh-pages@v1.0
      #   env:
      #     GITHUB_EMAIL: "tifayq@163.com"
      #     GITHUB_USERNAME: "Yin Qian"
      #     PUBLISH_REPO: https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git
      #     PUBLISH_BRANCH: gh-pages
      #     PUBLISH_DIR: ./gh-pages
      #     # DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      - name: Git Push Action
        # You may pin to the exact commit or the version.
        # uses: x-actions/git-push@ba04e59cd92b579c1df53fa8d398bec56f310906
        uses: x-actions/git-push@v1.0
        with:
          # git user email
          GITHUB_EMAIL: "tifayq@163.com" # optional, default is xiexianbin
          # git use username
          GITHUB_USERNAME: "Yin Qian" # optional, default is me@xiexianbin.cn
          # https:/<token>@github.com/owner/repo.git
          PUBLISH_REPO: https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git # optional
          # git branch
          PUBLISH_BRANCH: gh-pages # optional
          # dir to publish
          PUBLISH_DIR: ./gh-pages # optional
        
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
